### ISSUE TITLE
Adding line numbers to margin for templates meant to be edited/ reviewed

### ISSUE THREAD

**Issue by brentthorne** [rstudio/pagedown#115]
Is there a way to add a line number count in the left margin with paged.js? This would be very useful for templates made where documents need to be reviewed such as journal manuscripts, legal documents, government documents, etc..

I've tried combing through paged.js resources but haven't been able to find anything as of yet.

**Comment by RLesur** [comment]
TBH, I have no idea how to do that.
Maybe @fchasen or @JulieBlanc have some tips? 
I am going to ask to the Paged.js community on the dedicated [mattermost channel](https://mattermost.pagedmedia.org/).

**Comment by brentthorne** [comment]
That would be wonderful thank you!

**Comment by julientaq** [comment]
Hey @brentthorne and @RLesur (thanks to have connected us to here :D)

There is no way, with css, to count all line today, so you need a bit of hacking.

What i do, when i work with a baseline, is to number the lines on the whole page. it's a bit overkill, but it's pretty useful to design book with this: https://gist.github.com/julientaq/08d636a7a2b5f2824025256de0fca467 to have an example of how it works.

The problem is that it will works only if your content run on the same baseline (and header or change of font can easily screw everything up)

The other option is to count elements instead of lines. It's more reliable, but a bit less acurate (also, i would assume that you prefer to check for error in the context of paragraph, and not just a word)

this is how i would do it (im in the country this week, so i cant test, but here is my first shot) 

```css
body {
    counter-reset: element;
}

p, h1, h2, h3, h4, h5, h6 , blockquote, pre {
    counter-increment: element;
}
 
p::before, h1::before, h2::before, h3::before, h4::before, h5::before, h6 ::before, blockquote::before, pre::before {
        content: counter(element);
        position: absolute;
        left: -4ch;
        color: red;
    }

```

Let's keep talking when i get home next week, i've a couple of ideas :D
