### ISSUE TITLE
styling content inside of margin arguments

### ISSUE THREAD

**Issue by brentthorne** [rstudio/pagedown#116]
Hello again! 

I have a template which uses the page margin arguments to place a running footer with specific content like so:

```css
@page {
 @top-left {
   content: "Some content";
 }
}
```

Ideally I would like to be able to style the `content`, for example having "Some" be bold face but "content" be regular face. The issue is that I cannot place html tags into the `content` field as it just prints the value exactly as it is.

Is this a limitation of css or is there a way around it with js or knitr?

Thanks again!
