### ISSUE TITLE
notation in pagedown::business_card

### ISSUE THREAD

**Issue by mariakharitonova** [rstudio/pagedown#133]
Hi, I'm trying to create multiple cards using the business_cards template in pagedown (thank you for making this available!) and am having trouble understanding the multiple colon and bracket notation. E.g. in the example below, there are multiple colons before the code as well as the relevant variables (e.g. name) in the square brackets. Doesn't look like R markddown. Can you please direct me to appropriate documentation? I am trying to programmatically assign name, etc.  based on a data frame I will read it. Thank you!!

::::: {.wrapper data-repeat="12"}
[Jane Doe]{slot="name"}
[Miss Nobody]{slot="title"}
[+1 123-456-7890]{slot="phone"}
[jane.doe@example.com]{slot="email"}
[www.example.com]{slot="url"}

**Comment by RLesur** [comment]
These notations are Pandocs's fenced divs and bracketed spans.
Here is the relevant section in Pandoc's documentation: https://pandoc.org/MANUAL#divs-and-spans

If you prefer, you can write the same content with HTML markup (`<div></div>` and `<span></span>`)

**Comment by mariakharitonova** [comment]
Ah ok, thank you! I am new to pandoc conventions. So is there a way to define name, title, etc. variables that are in the square brackets [ ] from within the r chunks, so that I can assign names and titles programmatically? instead of listing one by one. If this is not the right place for this question, please let me know where I can ask it as I'm learning this. Thank you!!

**Comment by RLesur** [comment]
:thinking: I understand your goal, however I think I would adopt another strategy. 
**rmarkdown** is so powerful that we can do fun things!

Let assume that we want to automate these business cards:

```yaml
---
phone: "+1 844-448-1212"
email: "info@rstudio.com"
url: www.rstudio.com
address: |
  @rstudio
logo: "https://www.rstudio.com/wp-content/uploads/2016/09/RStudio-Logo-Blue-Gray-250.png"
person: 
  - name: Tareef Kawaf
    title: President of RStudio, Inc.
    repeat: 12
  - name: Yihui Xie
    title: Responsible for rmarkdown
    email: xie@yihui.name
    url: https://yihui.name
    repeat: 12
googlefonts: "Righteous"
paperwidth: 8.5in
paperheight: 11in
cols: 4
rows: 3
output: pagedown::business_card
---
```

The first trick that we can use is the following. With Pandoc, you can define YAML variables anywhere in your document (https://pandoc.org/MANUAL#extension-yaml_metadata_block). 
_Be careful, with **rmarkdown** you must have a top block defining the `output` format._

So, this document will be rendered exactly as the previous one:

```yaml
---
phone: "+1 844-448-1212"
email: "info@rstudio.com"
url: www.rstudio.com
address: |
  @rstudio
logo: "https://www.rstudio.com/wp-content/uploads/2016/09/RStudio-Logo-Blue-Gray-250.png"
googlefonts: "Righteous"
paperwidth: 8.5in
paperheight: 11in
cols: 4
rows: 3
output: pagedown::business_card
---

---
person: 
  - name: Tareef Kawaf
    title: President of RStudio, Inc.
    repeat: 12
  - name: Yihui Xie
    title: Responsible for rmarkdown
    email: xie@yihui.name
    url: https://yihui.name
    repeat: 12
---
```

Now, assume that we want to retrieve and prepare the data inside the R Markdown file. We could do something like that:

    ---
    phone: "+1 844-448-1212"
    email: "info@rstudio.com"
    url: www.rstudio.com
    address: |
      @rstudio
    logo: "https://www.rstudio.com/wp-content/uploads/2016/09/RStudio-Logo-Blue-Gray-250.png"
    googlefonts: "Righteous"
    paperwidth: 8.5in
    paperheight: 11in
    cols: 4
    rows: 3
    output: pagedown::business_card
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = FALSE)
    ```
    
    ```{r data-preparation}
    person <- list(
      list(
        name = "Tareef Kawaf",
        title = "President of RStudio, Inc.",
        `repeat` = 12L
      ),
      list(
        name = "Yihui Xie",
        title = "Responsible for rmarkdown",
        email = "xie@yihui.name",
        url = "https://yihui.name",
        `repeat` = 12L
      )
    )
    ```
    
    ---
    person: 
      - name: `r person[[1]]$name`
        title: `r person[[1]]$title`
        repeat: `r person[[1]][["repeat"]]`
      - name: `r person[[2]]$name`
        title: `r person[[2]]$title`
        email: `r person[[2]][["email"]]`
        url: `r person[[2]]$url`
        repeat: `r person[[2]][["repeat"]]`
    ---
    

This `Rmd` file leads to the same result. But this is not convenient to use.

The last step for automation is to generate the YAML block. This is possible with the `yaml::as.yaml()` function.

So the final step would be:

    ---
    phone: "+1 844-448-1212"
    email: "info@rstudio.com"
    url: www.rstudio.com
    address: |
      @rstudio
    logo: "https://www.rstudio.com/wp-content/uploads/2016/09/RStudio-Logo-Blue-Gray-250.png"
    googlefonts: "Righteous"
    paperwidth: 8.5in
    paperheight: 11in
    cols: 4
    rows: 3
    output: pagedown::business_card
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = FALSE)
    ```
    
    ```{r data-preparation}
    person <- list(
      list(
        name = "Tareef Kawaf",
        title = "President of RStudio, Inc.",
        `repeat` = 12L
      ),
      list(
        name = "Yihui Xie",
        title = "Responsible for rmarkdown",
        email = "xie@yihui.name",
        url = "https://yihui.name",
        `repeat` = 12L
      )
    )
    ```
    
    ---
    ```{r write-yaml, results='asis'}
    cat(yaml::as.yaml(list(person = person)))
    ```
    ---
    

The advantage that I see in this method is that you just have to prepare your data.
