### ISSUE TITLE
Blank page after TOC and at end of document

### ISSUE THREAD

**Issue by lu-dotcom** [rstudio/pagedown#145]
In the pagedown documentation example, there are blank pages present at the end of the table of contents section as well as the end of the document. The @page :blank selector in the CSS targets every blank page except for these two. Is there anyway to get rid of them through the rmd files, configuration settings, or CSS?

![image](https://user-images.githubusercontent.com/56412467/66602936-56fc1d00-eb68-11e9-9356-3fc0575c8615.png)

![image](https://user-images.githubusercontent.com/56412467/66602972-6d09dd80-eb68-11e9-9c91-500d76376ff9.png)

**Comment by RLesur** [comment]
The `pagedown::html_paged()` default style was designed for writing a book. That is why you observe these blank pages.  
Technically speaking, this style uses [_named pages_](https://gitlab.pagedmedia.org/tools/pagedjs-documentation/blob/master/Part07_Named-paged.md) defined in the [`default-page.css`](https://github.com/rstudio/pagedown/blob/master/inst/resources/css/default-page.css) stylesheet.

I understand very well that you would prefer not having these blank pages. For now, the only way is to replace the `default-page.css` file with your own custom file.

Here is an example. 
First, you need to create a custom file to define new rules for page breaks and page styling. Let's call this file `custom-page.css`. For instance, copy this content into this file:

```css
/* page size */
@page {
  size: 6in 9in;
}

/* store some string variables */
.shorttitle1 {
  string-set: h1-text content(text);
}

.shorttitle2 {
  string-set: h2-text content(text);
}

/* left page */
.running-h1-title {
  position: running(runningH1Title);
  width: var(--running-title-width);
  text-overflow: ellipsis;
  overflow: hidden;
}
.running-h1-title:before {
  content: string(h1-text);
}

@page :first {
  @top-left {
    content: none;
  }
  @top-right {
    content: none;
  }
  @bottom-right {
    content: none !important;
  }
  background-image: var(--front-cover);
  background-position: center;
  background-size: contain;
  background-repeat: no-repeat;
}

@page :left {
  @top-left {
    content: counter(page);
  }
}

@page :right {
  @top-right {
    content: counter(page);
  }
}

/* Front cover */
.front-cover {
  break-after: page;
}

/* page breaks; aka CSS fragmentation */
.level1 {
  break-before: page;
}
.section > h1, .section > h2, .section > h3, .section > h4, .section > h5, .section > h6 {
  break-after: avoid;
}
.footnotes {
  break-before: always;
  break-after: always;
}
.figure {
  break-inside: avoid;
}

/* do not break captions */
caption {
  break-inside: avoid;
  break-after: avoid;
}
```

You can use this custom stylesheet like that:

```markdown
---
title: "Title"
output:
  pagedown::html_paged:
    self_contained: false
    css:
      - default-fonts
      - default
      - custom-page.css
---

# First chapter

Some content
```

This question have been asked many times (see [here](https://twitter.com/jtrnyc/status/1176142069401882626) and [here](https://stackoverflow.com/questions/58365933/how-to-delete-blank-pages-in-rmarkdownpagedown)). 
I think that **pagedown** should offer a built-in option to disable these blank pages or provide other (customisable) templates without these blank pages.
