### ISSUE TITLE
Multiple landscape pages

### ISSUE THREAD

**Issue by thomasworville** [rstudio/pagedown#149]
Hi,

I'm wondering if it would be possible to create a multiple page report that is in landscape? For context, I'm trying to create a report that's visual-heavy (roughly 6 ggplots in a grid) for multiple companies in a report (so one page with the plots per company)

Thanks in advance.

**Comment by RLesur** [comment]
Hi,

Yes, it is possible to have a landscape report.  
We haven't yet implemented helpers to change paper size and page orientation (but I have some ideas on this subject).  

For now, here is a minimal example. First, here is an example of a CSS file for a landscape A4 paper:

```css
@media print {
  /* paper size and orientation */
  @page {
    size: A4 landscape;
  }
  
  /* page break */
  .level1 {
    break-before: page;
  }
}

/* screen viewer (optional) */
:root {
  --background: whitesmoke;
  --color-paper: white;
  --color-mbox: rgba(0, 0, 0, 0.2);
  --screen-pages-spacing: 5mm;
}

@media screen {
  body {
    background-color: var(--background);
    margin: var(--screen-pages-spacing) auto 0 auto;
  }
  .pagedjs_pages {
    display: flex;
    max-width: var(--pagedjs-width);
    flex: 0;
    flex-wrap: wrap;
    margin: 0 auto;
  }
  .pagedjs_page {
    background-color: var(--color-paper);
    box-shadow: 0 0 0 1px var(--color-mbox);
    flex-shrink: 0;
    flex-grow: 0;
    margin: auto auto var(--screen-pages-spacing) auto;
  }
}
```

Save this file to `landscape.css`. You can use it in the YAML header of your R Markdown like this:

```yaml
title: "Landscape mode"
date: "`r Sys.Date()`"
output:
  pagedown::html_paged:
    self_contained: false
    css: 
      - landscape.css
```

The Paged.js documentation provides more details on page size and orientation [here](https://gitlab.pagedmedia.org/tools/pagedjs-documentation/blob/master/Part04_Global-Layout.md#global-layout).
