### ISSUE TITLE
Document need for @import 'https://fonts.googleapis.com/css?family=Font';

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/pagedown#171]
I followed the advice in https://pagedown.rbind.io/#the-css-overriding-mechanism but my font would not change. Having played around a bit with the settings and the CSS I realised that I needed to add

```css
/* font location goes here:*/
@import 'https://fonts.googleapis.com/css?family=Comic+Neue';
```

Before the body to made the font available.

The whole of the CSS for custom font now looks like this:

```css
/* font location goes here:*/

@import 'https://fonts.googleapis.com/css?family=Comic+Neue';

body {
  font-family: "Comic Neue";
}
```

I'm pretty sure this should be documented. Will put in a Pull Request to do so!

Great package by the way guys, although I do think more documentation would help people new to CSS like me (and probably most people coming across the package).
