### ISSUE TITLE
Remove LOF and LOT from TOC

### ISSUE THREAD

**Issue by beatrizmilz** [rstudio/pagedown#221]
Hi! I'm using `pagedown::thesis_paged()` to write my thesis. I was able to do a lot of changes on the CSS and HTML template in order to adapt the template to the format rules of the university.

One thing that I was not able to do so far, and did not find content how to solve is:  I have a List of Figures (LOF) and List of Tables (LOT), but I do not want to add them in the Table of Contents (TOC).

So far, this is how my TOC appears:
![image](https://user-images.githubusercontent.com/42153618/114192620-14b1c880-9924-11eb-991b-5b80b1b02ae2.png)

In other sectors I used: `# Lista de abreviaturas e siglas {.unnumbered .unlisted}` but I have not been able to figure out how to pass this unlisted class to LOF and LOT. 

Is there any way to remove the LOF and LOT from the TOC?

**Comment by RLesur** [comment]
Hi @beatrizmilz!

We forgot to address this need in #16. 
This feature is not yet implemented but IMO, this is not a very difficult challenge, we just have to create new options (maybe `lof-untitled` and `lot-untitled`) here:

**Comment by beatrizmilz** [comment]
Hi @RLesur! Thank you so much for your answer. I have never edited the lua files, I'm trying to figure it out how to make this changes.

I saved this file in my  project in order to change it, and added in the yaml code of my document, in the pandoc args.
```
output:
  pagedown::thesis_paged: 
    template: template/thesis.html
    css: [template/thesis.css, template/custom.css]
    toc: true
    number_sections: yes
    pandoc_args:  ["--mathjax", "--lua-filter=template/loft.lua"]
    self_contained: no
```
I edited my copy of the lua file, and added 'unlisted' in this lines: [104](https://github.com/rstudio/pagedown/blob/66f760efc824ae17d97bc0898c5a7e3322fc8738/inst/resources/lua/loft.lua#L104) and  [114](https://github.com/rstudio/pagedown/blob/66f760efc824ae17d97bc0898c5a7e3322fc8738/inst/resources/lua/loft.lua#L114). 

But when I render the document, I get duplicate LOT and LOF (now I have 2 LOTs and 2 LOFS)... I think when I render, somehow the lua file from the package and the changed version are being used all at once.

Is there a way for me to indicate that only the changed file will be used?

I'm sorry if this question is out of the scope of pagedown...
