### ISSUE TITLE
Can't Apply CSS Color to Standart RMarkdown HTML file with chrome_print() [to PDF]

### ISSUE THREAD

**Issue by serdardindas** [rstudio/pagedown#233]
Hi All,

Firstly i want to thank you for this great package. This is my first issue in github, I hope I could done it well.

In pagedown package I create some basic examples with, poster_jacobs and resume templates. I always use them with chrome_print() to get PDF formats.

Now I try to chrome_print() standart Rmarkdown_HTML to PDF. With this HTML file I can apply CSS text-align but I couldnt apply CSS Colors to text in PDF.  In below you can see markdown YAML i use;

````
---
title: "Report"
output:
  html_document:
    css: formatstyle2.css
knit: pagedown::chrome_print
---
````

But when i try something different like  [ html_document: ] to => [ pagedown::html_paged: ] I can see CSS Color has applied.
But the html/pdf format of documents has changed.
````
---
title: "Report"
output:
  pagedown::html_paged:
    css: formatstyle2.css
knit: pagedown::chrome_print
---
````

Is there any way to use chrome_print() any standart Rmarkdown_HTML file with CSS Color can be seen?

I hope i could tell the situation properly. Thank you.

**Comment by cderv** [comment]
Thanks for opening this issue. You provided great information - just so you know I edited your post to get correct formatting. See https://yihui.org/issue/#please-format-your-issue-correctly

I think this issue is related to https://github.com/rstudio/pagedown/issues/229 in the fact that Bootstrap as some print style rule that will override any other when printing. 

`html_document` is using bootstrap, and it will have this rule 
````css
@media print
*, :after, :before {
    color: #000!important;
    text-shadow: none!important;
    background: 0 0!important;
    -webkit-box-shadow: none!important;
    box-shadow: none!important;
}
````

As you see, it will set any color to black - that is why when printing the color you changed does not apply. 

You would need to define the rule twice so that it override the one from bootstrap
````css
h1 {
  color: red;
}

/* Will override bootstrap print rule */
@media print {
  h1 {
    color: red !important;
  }
}
````

This is true only with Bootstrap 3 which is the default in `html_document` for now. 

You can use boostrap 4 which does not have this rule overriding color. You need a recent rmarkdown version. 

````
---
title: "Report"
output:
  html_document:
    theme:
      version: 4
    css: formatstyle2.css
knit: pagedown::chrome_print
---
````

I don't think there is anything specific to do in pagedown for this. 

**rmarkdown** will probably switch to bs4 by default some day and this will help. 
In the meantime, it needs to be dealt with custom rules.
