### ISSUE TITLE
Support to Sass

### ISSUE THREAD

**Issue by felipecrp** [rstudio/pagedown#243]
Hi,

When we include a `scss` file into the `pagedown:html_paged`, I get the following error:

```
Error: "print.scss" is not a valid built-in CSS filename. Use `pagedown:::list_css()` to view all built-in CSS filenames.
```

The frontmatter relevant part is next:

```yaml
output: 
    pagedown::html_paged:
      css:
        - print.scss
```

Maybe removing the filter for "valid" files may solve this issue.
