### ISSUE TITLE
Change the page size of the resume template

### ISSUE THREAD

**Issue by danielvartan** [rstudio/pagedown#285]
Hi there,

I was wondering if there's a simple way to change the page size of the resume template.

The actual page size is Letter (8.5 by 11 inches). Most European and Latin American countries use A4 (210 mm × 297 mm) as the standard.

**Comment by danielvartan** [comment]
This seems to do the trick.

```css
@page {
    size: A4 portrait;
}

@media screen and (min-width: 8.3in) {
    body {
        margin: auto;
        width: unset;
    }
}

.pagedjs_page {
    --pagedjs-pagebox-width: 8.3in !important;
    --pagedjs-pagebox-height: 11.7in !important;
}

:root {
    --page-width: var(--pagedjs-width);
    --pagedjs-width: 8.3in;
    --pagedjs-height: 11.7in;
    --pagedjs-width-right: var(--pagedjs-width);
    --pagedjs-height-right: var(--pagedjs-height);
    --pagedjs-width-left: var(--pagedjs-width);
    --pagedjs-height-left: var(--pagedjs-height);
    --pagedjs-pagebox-width: var(--pagedjs-width);
    --pagedjs-pagebox-height: var(--pagedjs-height);
    --sidebar-width: 11.5rem;
}
```
