### ISSUE TITLE
TOC with multiple pages not working, if build in `default.css` is not used

### ISSUE THREAD

**Issue by a-maldet** [rstudio/pagedown#304]
Hello!

Thanks for your awesome package!

I want to create customized reports with `pagedown::html_paged`.
But at the moment, I am struggling with a very basic question:
I assumed that the following two solutions would yield the same results:

- including `default.css`  via pagedown-default-name as usual: Setting `css: default` in the YAML header
- including `default.css` via filename: First copy `default.css` into report directory and then set option `css: default.css` in the YAML header

**The latter solution does not allow multipage TOC.**
(The Google Chrome console prints `Unable to layout item!`)

**Besides that, for reports with a smaller number of chapters the results seem to be identical.**

Am I doing something wrong, is this a bug or is my assumption wrong, that including CSS via filename and CSS via default name should behave the same?
If my assumption was wrong: How should I add my own `default.css`, when it differs from the build-in one?
Thanks a lot and happy new year!

Adrian

P.s.: My system setup and working examples are below

My Google chrome version is:
`Version 108.0.5359.125 (Offizieller Build) (32-Bit)`

The terminal command `pandoc --version` yields:
```
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
```

The console command `sessionInfo()` yields:

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=German_Austria.1252  LC_CTYPE=German_Austria.1252    LC_MONETARY=German_Austria.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Austria.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.2     xfun_0.31            bslib_0.3.1          purrr_0.3.4          rJava_1.0-6         
 [6] vctrs_0.4.1          generics_0.1.3       htmltools_0.5.2      yaml_2.3.5           utf8_1.2.1          
[11] rlang_1.0.2          later_1.3.0          pillar_1.7.0         jquerylib_0.1.4      glue_1.6.2          
[16] DBI_1.1.3            lifecycle_1.0.1      stringr_1.4.0        pagedown_0.19        rvest_1.0.2         
[21] evaluate_0.15        knitr_1.39           fastmap_1.1.0        httpuv_1.6.5         fansi_0.4.2         
[26] xlsxjars_0.6.1       highr_0.9            Rcpp_1.0.7           promises_1.2.0.1     xlsx_0.6.5          
[31] composerr_2.1.3      jsonlite_1.8.0       fs_1.5.0             mime_0.12            rmdmux_1.0.2        
[36] servr_0.24           digest_0.6.29        stringi_1.5.3        xaringan_0.25        bookdown_0.27       
[41] dplyr_1.0.8          styledTables_2.3.3   cli_3.2.0            tools_4.0.3          magrittr_2.0.3      
[46] sass_0.4.1           tibble_3.1.0         crayon_1.5.1         pkgconfig_2.0.3      tinytools_2.6.2     
[51] ellipsis_0.3.2       data.table_1.14.2    xml2_1.3.3           xlsxcollection_1.3.2 assertthat_0.2.1    
[56] rmarkdown_2.14       httr_1.4.3           rstudioapi_0.13      R6_2.5.1             compiler_4.0.3   
```

Below I included both cases for `example.Rmd`:

I use the command `xaringan::inf_mr("example.Rmd")` for starting the infinite moonreader.

**This code for `example.Rmd` is working:**

```
---
title: "Default CSS name: Multipage TOC is working"
output:
  pagedown::html_paged: 
    toc: true
    css:
      - default-page
      - default
toc-title: Table of contents
---

# Chapter1
# Chapter2
# Chapter3
# Chapter4
# Chapter5
# Chapter6
# Chapter7
# Chapter8
# Chapter9
# Chapter10
# Chapter11
# Chapter12
# Chapter13
# Chapter14
# Chapter15
# Chapter16
# Chapter17
# Chapter18
# Chapter19
# Chapter20
# Chapter21
# Chapter22
# Chapter23
# Chapter24
# Chapter25
# Chapter26
# Chapter27
# Chapter28
# Chapter29
# Chapter30
# Chapter31
# Chapter32
```

**This code for `example.Rmd` is NOT working:**
(The `default.css` of `pagedown` should be copied into the report directory first.)

```
---
title: "Default CSS name: Multipage TOC is NOT working"
output:
  pagedown::html_paged: 
    toc: true
    css:
      - default-page
      - default.css
toc-title: Table of contents
---

# Chapter1
# Chapter2
# Chapter3
# Chapter4
# Chapter5
# Chapter6
# Chapter7
# Chapter8
# Chapter9
# Chapter10
# Chapter11
# Chapter12
# Chapter13
# Chapter14
# Chapter15
# Chapter16
# Chapter17
# Chapter18
# Chapter19
# Chapter20
# Chapter21
# Chapter22
# Chapter23
# Chapter24
# Chapter25
# Chapter26
# Chapter27
# Chapter28
# Chapter29
# Chapter30
# Chapter31
# Chapter32
```
