### ISSUE TITLE
Some dots (leaders) appearing in code chunk when LOF is on 

### ISSUE THREAD

**Issue by cderv** [rstudio/pagedown#305]
Just noticed that while testing other things 

````markdown
---
title: "A Multi-page HTML Document"
author: "Yihui Xie and Romain Lesur"
date: "`r Sys.Date()`"
output:
  pagedown::html_paged:
    self_contained: false
lof: true # insert a list of figures
---

Some text 

```{r, echo = TRUE, fig.cap = 'A very simple plot'}
plot(1)
```
````

It renders to 
![image](https://user-images.githubusercontent.com/6791940/210334444-6060ba72-8a5f-4e8c-9fbc-7216a6eecad0.png)

See the dots in the code chunk. It seems to be there only when `lof: true` 

in term of HTML code, it seems to be some specific spans to be added 
````html
<span class="leaders" data-ref="638399fd-56b6-4f00-9825-2e2876f74cb3"></span>
````
With special CSS rule 
````css
.toc .leaders::before, .lot .leaders::before, .lof .leaders::before {
    float: left;
    width: 0;
    white-space: nowrap;
    content: ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ";
}
````

Maybe only some CSS to fix 🤔
