### ISSUE TITLE
Rendering `*.qmd` vignette files

### ISSUE THREAD

**Issue by elgabbas** [rstudio/pagedown#337]
Hello,

Does `pagedown` support rendering `*.qmd` vignette files? I saved the following simple script in the `vignettes/AA.qmd`.

```
---
title: "TITLE"
output: html_document
author: "AUTHOR"
date: "2025-02-19"
date-modified: "`r format(Sys.time(), '%d %B, %Y')`"
editor_options: 
  chunk_output_type: console
editor: 
  markdown: 
    wrap: 72
execute: 
  eval: false
format:
  html:
    embed-resources: true
    code-overflow: wrap
    page-layout: full
    toc: true
    toc-title: "TOC_TITLE"
    toc-expand: true
    toc-depth: 2
    number-sections: true
    link-external-icon: true
    link-external-newwindow: true
---

# Level1
SOME TEXT

## Level2
SOME TEXT

### Level3
SOME TEXT
```

I get the following error when using `pkgdown::build_articles()` (although the same script works as expected when clicking on the knit button of RStudio):

```
── Building articles ──────────────────────────────────────────────
Writing articles/index.html
Reading vignettes/AA.qmd
Running `quarto render`
Error in `quarto::quarto_render()`:
✖ Error running quarto cli.
ℹ Rerun with `quiet = FALSE` to see the full error message.
Caused by error:
! System command 'quarto.exe' failed
Run `rlang::last_trace()` to see where the error occurred.
```

By renaming the same file from `vignettes/AA.qmd` to `vignettes/AA.Rmd`,  `pkgdown::build_articles()` works as expected, although with some options not considered in the resulted HTML; e.g.
- it does not show the updated date
- can not switch off `toc` nor change toc title `toc-title` or having a numbered sections `number-sections`
- toc does not show smoothly up to e.g. level 3:  toc-depth: 3, only level 1 and 2 are shown
