### ISSUE TITLE
Probleme for rendering html_paged document when usint accent in titles and TOC

### ISSUE THREAD

**Issue by sylvaine31** [rstudio/pagedown#339]
Hi,

The bug appeared after I installed the new RStudio version 2025.05.0 Build 496 this morning.

Here is a minimal reproducible example:

````
---
title: "Test"
author: "moi"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  pagedown::html_paged:
    toc: true
    toc_depth: 2
---

# Ploup

## Présence d'une DAACT

````
There is no error message, but the generated HTML file is blank.

Here are additional observations:

- If I use output: html_document, everything works fine.
- If I use pagedown::html_paged without the TOC, it works fine.
- If I use pagedown::html_paged with the TOC but remove the accent in the second-level heading, it also works.

So the problem seems to come from the combination of html_paged with toc: true and a title containing a non-ASCII character (accented letter) at level 2 or deeper.

System info:

- RStudio version: 2025.05.0 Build 496
- R version: 4.3.3
- pagedown version: 0.22
