### ISSUE TITLE
A convention for specifying short titles

### ISSUE THREAD

**Issue by yihui** [rstudio/pagedown#4]
When a section header is too long, its original text may not be suitable for a running header. In this case, we need a shorter version. One possible way is to use [bracketed spans](http://pandoc.org/MANUAL.html#divs-and-spans), e.g.

```markdown
# Hello World

[hello]{.shorttitle}
```

Then we define something like

```css
.shorttitle {
  display: none;
}
.shorttitle, h1 {
  string-set: h1-text content(text);
}
@page {
  @top-right {
    content: string(h1-text);
  }
}
```

I haven't tested it. We need to make sure `string(h1-text)` gets the text from `.shorttitle` instead of `h1` when both are present on a page.

**Comment by RLesur** [comment]
In order to keep track, the following CSS rules do not work yet:
```css
@page :left {
  @top-left {
    content: counter(page);
  }
  @top-right {
    content: string(h1-text);
    white-space: nowrap !important;
    width: 2.5in;
    text-overflow: ellipsis;
    overflow: hidden;
  }
}
```
