### ISSUE TITLE
Issues with adding altmetric scores

### ISSUE THREAD

**Issue by dktanwar** [rstudio/pagedown#76]
Adding altmetric scores:

```rmarkdown
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>

<div class='altmetric-embed' data-badge-popover='bottom' data-doi='10.1016/S0140-6736(11)61619-x'></div>
```

It wors with `.Rmd` --> `.html_document`, but **not for `pagedown::html_resume`**

**Comment by RLesur** [comment]
This comes from the fact that Paged.js builds the document before the altmetric badge is retrieved.
You need to synchronize the altmetric JavaScript library with the Paged.js library by using the `altmetric:show` event as described in the [altmetric badge documentation](https://api.altmetric.com/embeds.html).
IMO, the most simple way is:
- remove the Paged.js auto mode (with `window.PagedConfig.auto = false;`)
- trigger Paged.js when the `altmetric:show` event is fired with `PagedPolyfill.preview();`

**Comment by dktanwar** [comment]
Basically, you want me to try to do this?

```css
/* Paged.js viewer */

@media screen {
  body {
    background-color: var(--viewer-background-color);
    margin: 0; /* for mobile */
    width: calc(var(--width) + 2 * var(--viewer-pages-spacing)); /* for mobile */
    window.PagedConfig.auto: false;
    PagedPolyfill.preview();
  }
```
