### ISSUE TITLE
code_folding?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/pagedown#90]
Is there any plan to add a `code_folding` option to `pagedown::html_paged:` ? I tried the following but it did not work as expected:

```
output:
  pagedown::html_paged:
    theme: default
    code_folding: hide
    toc: false
    # change to true for a self-contained document, but it'll be a litte slower for Pandoc to render
    self_contained: true
```
