### ISSUE TITLE
How to use academic icons?

### ISSUE THREAD

**Issue by Dr-Joe-Roberts** [rstudio/pagedown#94]
Hello, 

Is it possible to incorporate academicons (https://jpswalsh.github.io/academicons/) into a pagedown CV? If so, how?

Thanks.

**Comment by RLesur** [comment]
As in any R Markdown HTML format, it is possible to use academicons. I see two solutions, pick the one you prefer.

### Use the CSS served by RawGit

As stated in [the academicons documentation](https://jpswalsh.github.io/academicons#alongside-font-awesome), you can use the RawGit service to refer to its CSS (you need an internet connexion). You need to modify your YAML header as follows:
```yaml
---
title: "Lijia Yu's resume"
author: Lijia Yu
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    self_contained: false
    css:
    - resume
    - https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css
---
```
Then, you can use academicons in your document, for instance:
```html
<i class="ai ai-google-scholar-square"></i>
```

### Use the [ropenscilabs/icon](https://github.com/ropenscilabs/icon) package

If you need an offline solution, you can install the development version of [ropenscilabs/icon](https://github.com/ropenscilabs/icon).
Therefore, you can insert an academicons icon with:
    
    `r icon::ai("academia")`
